export interface Hymn {
  number: string;
  name: string;
}

// Default hymns database - you can expand this list with actual ICM hymns
export const hymnsDatabase: Hymn[] = [
  { "number": "1", "name": "O SANGUE DE JESUS TEM PODER" },
  { "number": "2", "name": "O SANGUE DE JESUS TEM PODER PARA SALVAR" },
  { "number": "3", "name": "CLAMO A TI" },
  { "number": "4", "name": "QUANDO TE PROSTRARES" },
  { "number": "5", "name": "CLAMANDO ESTOU" },
  { "number": "6", "name": "JESUS, Ó MEU JESUS" },
  { "number": "7", "name": "NESTA HORA EM ORAÇÃO" },
  { "number": "8", "name": "PELO SANGUE DE JESUS" },
  { "number": "9", "name": "SENHOR, ME CHEGO A TI" },
  { "number": "10", "name": "VAMOS LAVAR AS VESTES" },
  { "number": "11", "name": "REVESTE, SENHOR, TEU POVO" },
  { "number": "12", "name": "HÁ VITÓRIA PARA MIM" },
  { "number": "13", "name": "PÕE TEU SANGUE SOBRE MIM" },
  { "number": "14", "name": "EM TEU ALTAR, SENHOR" },
  { "number": "15", "name": "CLAMAREI, CLAMAREI" },
  { "number": "16", "name": "SE ANDARMOS NA LUZ" },
  { "number": "17", "name": "EM TUA PRESENÇA ENTRAMOS" },
  { "number": "18", "name": "PROSTRADO ESTOU DIANTE DE TI" },
  { "number": "19", "name": "TEU POVO CLAMA" },
  { "number": "20", "name": "O TEU PECADO TU QUERES DEIXAR?" },
  { "number": "21", "name": "NESTA HORA DE CLAMOR" },
  { "number": "22", "name": "BENDITO SEJA O CORDEIRO" },
  { "number": "23", "name": "SENHOR, OUVE A MINHA ORAÇÃO" },
  { "number": "24", "name": "EIS O CORDEIRO DE DEUS" },
  { "number": "25", "name": "SENHOR, A TI CLAMO" },
  { "number": "26", "name": "SEJA SÓ O SENHOR LOUVADO AQUI" },
  { "number": "27", "name": "CORDEIRO ETERNO" },
  { "number": "28", "name": "O PODER DO SANGUE DE JESUS" },
  { "number": "29", "name": "TRANSBORDA-ME, SENHOR" },
  { "number": "30", "name": "OH! QUE PRECIOSO SANGUE" },
  { "number": "31", "name": "JUNTO A TI SUPLICO, Ó PAI" },
  { "number": "32", "name": "O SANGUE DE JESUS, VERTIDO ALI NA CRUZ" },
  { "number": "33", "name": "EU ME PROSTRO EM TEU ALTAR" },
  { "number": "34", "name": "QUANDO BUSCAMOS" },
  { "number": "35", "name": "A MEU SENHOR" },
  { "number": "36", "name": "CRUCIFICADO FOI MEU JESUS" },
  { "number": "37", "name": "NESTA HORA ESQUEÇO O MUNDO" },
  { "number": "38", "name": "PELO SANGUE DE JESUS IREI CLAMAR" },
  { "number": "39", "name": "JESUS, TU ÉS O MEU DEUS" },
  { "number": "40", "name": "OH! QUE SANGUE PODEROSO" },
  { "number": "41", "name": "ALÉM DO VÉU EU QUERO ESTAR" },
  { "number": "42", "name": "SENHOR, SUPLICO A TI EM ORAÇÃO" },
  { "number": "43", "name": "VOU CLAMAR" },
  { "number": "44", "name": "CONFORME A TUA INFINITA GRAÇA" },
  { "number": "45", "name": "NOS ÁTRIOS DO SENHOR ENTRAMOS" },
  { "number": "46", "name": "AO SENTIR O TEU PERDÃO" },
  { "number": "47", "name": "É TEU SANGUE" },
  { "number": "48", "name": "PELO SANGUE DE JESUS EU VOU CLAMAR" },
  { "number": "49", "name": "NA HORA EM QUE EU QUISER FALAR COM DEUS" },
  { "number": "50", "name": "O SANGUE DE JESUS" },
  { "number": "51", "name": "O CORDEIRO QUE NA CRUZ MORREU" },
  { "number": "52", "name": "ESCUTA-ME, SENHOR" },
  { "number": "53", "name": "O SANGUE DO CORDEIRO DE DEUS" },
  { "number": "54", "name": "HÁ VITÓRIA SEMPRE EM TI, SENHOR" },
  { "number": "55", "name": "SENHOR, MEU DEUS E PAI" },
  { "number": "56", "name": "VITÓRIA SOBRE VITÓRIA" },
  { "number": "57", "name": "EM FERVENTE ORAÇÃO" },
  { "number": "58", "name": "ATENDE A VOZ DO MEU CLAMOR" },
  { "number": "59", "name": "SE ORARMOS AO SENHOR" },
  { "number": "60", "name": "BEM DE MANHÃ, EMBORA O CÉU SERENO" },
  { "number": "61", "name": "SUBA A MINHA ORAÇÃO" },
  { "number": "62", "name": "NO SILÊNCIO DA NOITE" },
  { "number": "63", "name": "INVOCA-ME E TE RESPONDEREI" },
  { "number": "64", "name": "BRILHE SOBRE MIM" },
  { "number": "65", "name": "QUANDO O DIA AMANECE" },
  { "number": "66", "name": "DE MADRUGADA EU BUSCO A FACE DO SENHOR" },
  { "number": "67", "name": "TOCA PELA FÉ" },
  { "number": "68", "name": "LÁ NO CIMO DO MONTE" },
  { "number": "69", "name": "O ANJO DO SENHOR ESTÁ PASSEANDO" },
  { "number": "70", "name": "PRECIOSAS SÃO AS HORAS" },
  { "number": "71", "name": "VEM, AMADO MEU" },
  { "number": "72", "name": "É PRECISO CONFIAR E BUSCAR A DEUS" },
  { "number": "73", "name": "DEUS ESTÁ NO TEMPLO" },
  { "number": "74", "name": "SEI, SENHOR" },
  { "number": "75", "name": "SENTE EM TUA FACE O ROÇAR" },
  { "number": "76", "name": "NESTA NOITE FELIZ" },
  { "number": "77", "name": "VEM, VISITA TUA IGREJA" },
  { "number": "78", "name": "UMA VOZ MANSA E DELICADA" },
  { "number": "79", "name": "DEUS ESTÁ PRESENTE ENTRE PECADORES COMO NÓS" },
  { "number": "80", "name": "VIVES MUITO ALÉM DO CÉU" },
  { "number": "81", "name": "GRANDE DEUS, ÚNICO DEUS" },
  { "number": "82", "name": "CADA INSTANTE" },
  { "number": "83", "name": "MAIS UMA VEZ" },
  { "number": "84", "name": "ATENDE, SENHOR, A MINHA ORAÇÃO" },
  { "number": "85", "name": "ENVIA A TUA LUZ" },
  { "number": "86", "name": "EM TEU NOME" },
  { "number": "87", "name": "MEU PECADO RESGATADO" },
  { "number": "88", "name": "DAS PROFUNDEZAS" },
  { "number": "89", "name": "DAS PROFUNDEZAS CLAMO A TI, Ó SENHOR!" },
  { "number": "90", "name": "EM TUAS MÃOS, SENHOR" },
  { "number": "91", "name": "JESUS, A MINH'ALMA TEM SEDE DE TI" },
  { "number": "92", "name": "PAI CELESTE" },
  { "number": "93", "name": "LOGO DE MANHÃ" },
  { "number": "94", "name": "BENDITA A HORA DE ORAÇÃO" },
  { "number": "95", "name": "BUSCAR-ME-EIS" },
  { "number": "96", "name": "COM A MINHA VOZ CLAMO AO SENHOR (SI 142)" },
  { "number": "97", "name": "BUSCOU-ME COM TERNURA" },
  { "number": "98", "name": "ONDE ESTARIA EU?" },
  { "number": "99", "name": "UM DIA JESUS ACHOU-ME" },
  { "number": "100", "name": "EU ME LEMBRO QUANDO JESUS ME TOCOU" },
  { "number": "101", "name": "QUEM ERA EU ANTES DE CONHECER" },
  { "number": "102", "name": "MARAVILHOSO E SUBLIME PRA MIM" },
  { "number": "103", "name": "A MINH'ALMA ESTAVA LONGE DO CAMINHO DO CÉU" },
  { "number": "104", "name": "VIVI TÃO LONGE DO SENHOR" },
  { "number": "105", "name": "PERDIDO FOI QUE ELE ME ENCONTROU" },
  { "number": "106", "name": "PELA FÉ SOMOS SALVOS" },
  { "number": "107", "name": "QUANDO ANDAVA NO MUNDO ESCRAVIZADO" },
  { "number": "108", "name": "ISRAEL SAIU DO EGITO" },
  { "number": "109", "name": "A MINHA VIDA TÃO VAZIA" },
  { "number": "110", "name": "OH! QUÃO CEGO ANDEI E PERDIDO VAGUEI" },
  { "number": "111", "name": "O POVO QUE ANDAVA EM TREVAS" },
  { "number": "112", "name": "UMA LUZ BRILHOU EM MEU CAMINHO" },
  { "number": "113", "name": "JESUS, A LUZ DIVINA" },
  { "number": "114", "name": "AS RIQUEZAS DO MUNDO" },
  { "number": "115", "name": "GRAÇAS DOU, Ó SENHOR" },
  { "number": "116", "name": "ACHEI SALVAÇÃO" },
  { "number": "117", "name": "COMO DESISTIR DESTE GRANDE AMOR?" },
  { "number": "118", "name": "Ó SENHOR, DEUS DE ISRAEL (EDIFIQUEI UMA CASA)" },
  { "number": "119", "name": "JESUS, NOME PRECIOSO" },
  { "number": "120", "name": "JESUS CRISTO MUDOU MEU VIVER" },
  { "number": "121", "name": "TUDO, Ó CRISTO, A TI ENTREGO" },
  { "number": "122", "name": "AMO AO SENHOR PORQUE ELE ME OUVIU" },
  { "number": "123", "name": "SEGUIR-TE-EI" },
  { "number": "124", "name": "PEREGRINANDO POR SOBRE OS MONTES" },
  { "number": "125", "name": "PELA FÉ EU CAMINHO" },
  { "number": "126", "name": "QUERO PROSSEGUIR" },
  { "number": "127", "name": "ESTOU A CAMINHAR" },
  { "number": "128", "name": "QUANDO A MÃO DE DEUS EM MIM VEIO TOCAR" },
  { "number": "129", "name": "FELICIDADE É TER CRISTO AO MEU LADO" },
  { "number": "130", "name": "TENHO GRANDE GOZO" },
  { "number": "131", "name": "ÀS VEZES, ALGUÉM ME PERGUNTA" },
  { "number": "132", "name": "JÁ NÃO ESTOU SOZINHO" },
  { "number": "133", "name": "EU ESTAVA SÓ, SEM O SENHOR" },
  { "number": "134", "name": "QUE SEGURANÇA, TENHO EM JESUS" },
  { "number": "135", "name": "EM MEU CORAÇÃO" },
  { "number": "136", "name": "ESTA PAZ QUE SINTO EM MINH'ALMA" },
  { "number": "137", "name": "QUE DOCE VOZ TEM MEU SENHOR" },
  { "number": "138", "name": "HÁ SEMPRE ALGUÉM QUE NÃO PROVOU" },
  { "number": "139", "name": "NÃO SEI POR QUE DE DEUS O AMOR" },
  { "number": "140", "name": "AS MUITAS ÁGUAS" },
  { "number": "141", "name": "O AMOR DE DEUS POR NÓS" },
  { "number": "142", "name": "CRISTO, MEU MESTRE, SEMPRE HÁ DE AMAR-ME" },
  { "number": "143", "name": "SE NÃO FOSSE O AMOR" },
  { "number": "144", "name": "JESUS, AGORA EU BEM SEI" },
  { "number": "145", "name": "É O AMOR DE DEUS" },
  { "number": "146", "name": "EXISTE UM ALGUÉM QUE CUIDA DE MIM" },
  { "number": "147", "name": "CRISTO É TUDO PARA MIM" },
  { "number": "148", "name": "UMA CERTA VEZ, JESUS CRISTO" },
  { "number": "149", "name": "JESUS FEZ A PROMESSA" },
  { "number": "150", "name": "VOU CONTAR-VOS O QUE PENSO DO MEU MESTRE" },
  { "number": "151", "name": "CRISTO JESUS É O MEU BOM SALVADOR" },
  { "number": "152", "name": "MAIS PERTO DE JESUS" },
  { "number": "153", "name": "CRISTO, NOME MAIS ALTO" },
  { "number": "154", "name": "Ó TU QUE HABITAS ENTRE OS QUERUBINS" },
  { "number": "155", "name": "HÁ UM SER QUE VIVE EM MIM" },
  { "number": "156", "name": "TOTALMENTE DESEJÁVEL É O MEU AMADO" },
  { "number": "157", "name": "CRISTO É A ROSA MAIS BELA" },
  { "number": "158", "name": "JESUS, O LÍRIO DOS VALES" },
  { "number": "159", "name": "ELE É A ROSA DE SAROM" },
  { "number": "160", "name": "EU SOU DO MEU AMADO E ELE ME TEM AFEIÇÃO" },
  { "number": "161", "name": "ERA UMA OLIVEIRA" },
  { "number": "162", "name": "GRANDIOSO PARA MIM" },
  { "number": "163", "name": "TENHO UMA PEDRA VIVA" },
  { "number": "164", "name": "É BASTANTE PARA MIM A TUA GRAÇA" },
  { "number": "165", "name": "MARAVILHOSA GRAÇA" },
  { "number": "166", "name": "Ó AMADO DE MINH'ALMA" },
  { "number": "167", "name": "AMO AO MEU SENHOR" },
  { "number": "168", "name": "TU ÉS FIEL, SENHOR" },
  { "number": "169", "name": "COMO A FLOR DO CAMPO" },
  { "number": "170", "name": "EU SOU TÃO FELIZ COM O MEU JESUS" },
  { "number": "171", "name": "O AMOR DE JESUS É GRANDE" },
  { "number": "172", "name": "SENHOR, TE AMO, TE AMO" },
  { "number": "173", "name": "QUANDO JESUS UM DIA" },
  { "number": "174", "name": "A MINHA HERANÇA É O SENHOR" },
  { "number": "175", "name": "DESDE O DIA EM QUE TE CONHECI" },
  { "number": "176", "name": "NÃO EXISTE OUTRO AMOR IGUAL AO TEU, SENHOR" },
  { "number": "177", "name": "SEMPRE VOU LEMBRAR O QUE FIZESTE POR MIM" },
  { "number": "178", "name": "O DEUS A QUEM SERVIMOS" },
  { "number": "179", "name": "PELA FÉ EU POSSO CONTEMPLAR JESUS" },
  { "number": "180", "name": "ENCONTREI O GRANDE AMOR" },
  { "number": "181", "name": "EM TI EU ENCONTRO, Ó DEUS, TODA PAZ" },
  { "number": "182", "name": "COMO É BOM SERVIR AO SENHOR" },
  { "number": "183", "name": "A MINHA ALEGRIA" },
  { "number": "184", "name": "REDENTOR ONIPOTENTE" },
  { "number": "185", "name": "JESUS, SENHOR, ME CHEGO A TI (EU VENHO COMO ESTOU)" },
  { "number": "186", "name": "PARA QUEM IREMOS NÓS?" },
  { "number": "187", "name": "MINH'ALMA TEM SEDE DE TI" },
  { "number": "188", "name": "VENHO, SENHOR, MINHA VIDA OFERECER" },
  { "number": "189", "name": "DEPENDO DE TI, SENHOR" },
  { "number": "190", "name": "TODO O MEU SER TE AMA" },
  { "number": "191", "name": "EU QUERO SENTIR" },
  { "number": "192", "name": "JESUS, JESUS, EU TE AMO" },
  { "number": "193", "name": "AS MUITAS ÁGUAS NÃO PODERIAM APAGAR" },
  { "number": "194", "name": "QUERO ANDAR EM TEU CAMINHO, SENHOR" },
  { "number": "195", "name": "GRANDE AMOR, Ó GRANDE AMOR" },
  { "number": "196", "name": "O GRANDE AMOR DO MEU SENHOR" },
  { "number": "197", "name": "HOJE QUERO SOMENTE AGRADECER" },
  { "number": "198", "name": "ELE É A MINHA ALEGRIA" },
  { "number": "199", "name": "COMO É BOM OUVIR TUA VOZ" },
  { "number": "200", "name": "EU SIRVO UM DEUS" },
  { "number": "201", "name": "SEU CORPO CANSADO PELAS CAMINHADAS" },
  { "number": "202", "name": "HÁ UMA FONTE ABERTA NO CALVÁRIO" },
  { "number": "203", "name": "JESUS IA SUBINDO O MONTE" },
  { "number": "204", "name": "MORRI NA CRUZ POR TI" },
  { "number": "205", "name": "JESUS IA SEGUINDO" },
  { "number": "206", "name": "PAI, A TI ENTREGO O MEU ESPÍRITO" },
  { "number": "207", "name": "DEUS ENVIOU SEU FILHO AMADO" },
  { "number": "208", "name": "DEUS AMOU O MUNDO DE TAL MANEIRA" },
  { "number": "209", "name": "DEUS O SEU FILHO ENVIOU" },
  { "number": "210", "name": "UM DIA JESUS DESCEU DA SUA GLÓRIA" },
  { "number": "211", "name": "CORTARAM O MADEIRO" },
  { "number": "212", "name": "RUDE CRUZ" },
  { "number": "213", "name": "CRISTO CAMINHAVA EM DIREÇÃO À CRUZ" },
  { "number": "214", "name": "DOIS DISCÍPULOS NO CAMINHO DE EMAÚS" },
  { "number": "215", "name": "CERTO HOMEM TÃO NOBRE" },
  { "number": "216", "name": "SOMOS TEU POVO" },
  { "number": "217", "name": "DEIXOU O ESPLENDOR DE SUA GLÓRIA" },
  { "number": "218", "name": "POR AMOR JESUS MORREU" },
  { "number": "219", "name": "POR AMOR" },
  { "number": "220", "name": "NÃO HÁ AMOR IGUAL" },
  { "number": "221", "name": "JESUS, EM TUA PRESENÇA" },
  { "number": "222", "name": "EIS QUE ESTOU À PORTA" },
  { "number": "223", "name": "ONDE ESTÁ O CORDEIRO?" },
  { "number": "224", "name": "ERA UM PECADOR, ANDAVA SEM JESUS" },
  { "number": "225", "name": "JESUS É MELHOR, SIM, QUE OURO E BENS" },
  { "number": "226", "name": "O SENTIDO DE VIVER" },
  { "number": "227", "name": "SÓ JESUS TE PODE DAR O QUE PROCURAS" },
  { "number": "228", "name": "ENTREGA O TEU CAMINHO AO SENHOR" },
  { "number": "229", "name": "AO POÇO DE JACÓ CHEGOU JESUS" },
  { "number": "230", "name": "FONTE DE ÁGUAS VIVAS" },
  { "number": "231", "name": "QUEM ME DÁ ÁGUA" },
  { "number": "232", "name": "QUEM BEBER DA ÁGUA QUE EU LHE DER" },
  { "number": "233", "name": "VOU GUIAR-TE A UMA RICA FONTE" },
  { "number": "234", "name": "DEUS HOJE QUER TE FALAR" },
  { "number": "235", "name": "MANSO E SUAVE JESUS ESTÁ CHAMANDO" },
  { "number": "236", "name": "OUVE A VOZ DE JESUS" },
  { "number": "237", "name": "EIS MENSAGEM DO SENHOR" },
  { "number": "238", "name": "TANTO TEMPO JÁ FAZ QUE O CHAMADO DIVINAL" },
  { "number": "239", "name": "DEIXA DEUS FALAR AO TEU CORAÇÃO" },
  { "number": "240", "name": "SE CANSADO TU ESTÁS" },
  { "number": "241", "name": "MEU AMADO FILHO" },
  { "number": "242", "name": "SE ESTA NOITE DEUS PEDIR TUA ALMA" },
  { "number": "243", "name": "JÁ ACHEI UMA FLOR GLORIOSA" },
  { "number": "244", "name": "EU DESCI PARA O VALE DE BÊNÇÃO E PAZ" },
  { "number": "245", "name": "POR ONDE QUER QUE EU VÁ" },
  { "number": "246", "name": "SE EM TEU VIVER" },
  { "number": "247", "name": "SE ANDA TRISTE O TEU VIVER" },
  { "number": "248", "name": "SE VOCÊ QUISER SABER" },
  { "number": "249", "name": "SE EM TUA VIDA FALTA PAZ" },
  { "number": "250", "name": "SE TU PROCURAS PELA PAZ" },
  { "number": "251", "name": "A PAZ QUE TU PROCURAS" },
  { "number": "252", "name": "SE DISPUSERES O TEU CORAÇÃO (JÓ 11.13-19)" },
  { "number": "253", "name": "SE DISPUSERES O TEU CORAÇÃO" },
  { "number": "254", "name": "OLHAI PARA O ALTO" },
  { "number": "255", "name": "MEU CORAÇÃO ENGRANDECE AO SENHOR (CÂNTICO DE VITÓRIA!)" },
  { "number": "256", "name": "NÃO MAIS VIVO EU, MAS CRISTO VIVE EM MIM" },
  { "number": "257", "name": "TUDO SE FEZ NOVO" },
  { "number": "258", "name": "SE TU ESTÁS TÃO LONGE DO SENHOR" },
  { "number": "259", "name": "COMO UM BOM PASTOR" },
  { "number": "260", "name": "DEUS ESTÁ PRESENTE AQUI NESTE LUGAR" },
  { "number": "261", "name": "CRISTO CAMINHAVA LENTAMENTE" },
  { "number": "262", "name": "QUERO QUE VOCÊ CONHEÇA" },
  { "number": "263", "name": "QUERES IR PRA GLÓRIA?" },
  { "number": "264", "name": "OH! QUE BELOS HINOS HOJE LÁ NO CÉU" },
  { "number": "265", "name": "LEVA TU CONTIGO O NOME" },
  { "number": "266", "name": "TODOS OS POVOS" },
  { "number": "267", "name": "QUANDO JESUS SEU SANGUE VERTEU" },
  { "number": "268", "name": "JESUS É O CORDEIRO" },
  { "number": "269", "name": "NÃO SEI SE OUVISTE FALAR" },
  { "number": "270", "name": "SE TU PEDISTE UM SINAL" },
  { "number": "271", "name": "O CAMINHO QUE NOS LEVA AO CÉU É JESUS" },
  { "number": "272", "name": "NOVO CAMINHO" },
  { "number": "273", "name": "O SENHOR É A ALEGRIA" },
  { "number": "274", "name": "SE EM TUA VIDA NÃO ENCONTRAS PAZ E LUZ" },
  { "number": "275", "name": "UM MILAGRE É" },
  { "number": "276", "name": "AINDA QUE OS SEUS SONHOS" },
  { "number": "277", "name": "ROCHA ETERNA" },
  { "number": "278", "name": "A NOVA DO EVANGELHO" },
  { "number": "279", "name": "QUERO ESTAR AO PÉ DA CRUZ" },
  { "number": "280", "name": "HÁ HOJE ALGUÉM ESPERANDO" },
  { "number": "281", "name": "ESTE MUNDO NÃO TEM A SUA PAZ" },
  { "number": "282", "name": "QUEM É QUE DÁ ÁGUA AO SEDENTO?" },
  { "number": "283", "name": "O MUNDO NÃO SABE" },
  { "number": "284", "name": "O AMOR DE DEUS É GRANDE" },
  { "number": "285", "name": "TU QUE ANDAS SÓ E TRISTE SEM SABER O CAMINHO" },
  { "number": "286", "name": "UM DIA EU QUIS TE DEIXAR" },
  { "number": "287", "name": "NÃO TINHA PARECER" },
  { "number": "288", "name": "BASTA DIZERES O QUE QUERES" },
  { "number": "289", "name": "ESTENDE TUA MÃO" },
  { "number": "290", "name": "O QUE OS OLHOS NUNCA VIRAM" },
  { "number": "291", "name": "SEMPRE QUE QUISERES FALAREI CONTIGO" },
  { "number": "292", "name": "AO SENTIR O MUNDO AO MEU REDOR" },
  { "number": "293", "name": "ALMA CANSADA" },
  { "number": "294", "name": "JESUS IA CAMINHANDO (CANTA MEU POVO)" },
  { "number": "295", "name": "DAS PROFUNDEZAS CLAMO A TI, SENHOR" },
  { "number": "296", "name": "TODA A MINHA DOR JESUS LEVOU" },
  { "number": "297", "name": "EM ME VINDO O TEMOR" },
  { "number": "298", "name": "NEM SEMPRE ENTENDEMOS" },
  { "number": "299", "name": "HÁ MOMENTOS QUE AS PALAVRAS NÃO RESOLVEM" },
  { "number": "300", "name": "QUANDO PARECE QUE TUDO ACABOU" },
  { "number": "301", "name": "QUANDO A TRISTEZA SURGIR" },
  { "number": "302", "name": "SE A VIDA PARECE PESADA" },
  { "number": "303", "name": "SE NÃO PUDERES MAIS" },
  { "number": "304", "name": "BASTA QUE ME TOQUES, SENHOR" },
  { "number": "305", "name": "O SENHOR É A MINHA LUZ" },
  { "number": "306", "name": "MEDO TENS QUE O TENTADOR TE VÁ VENCER?" },
  { "number": "307", "name": "PELO VALE ESCURO SEGUIREI JESUS" },
  { "number": "308", "name": "PROFUNDOS VALES EU TEREI DE PASSAR" },
  { "number": "309", "name": "OH! POR QUE DUVIDAR?" },
  { "number": "310", "name": "MESTRE, O MAR SE REVOLTA" },
  { "number": "311", "name": "SÓ UMA VOZ ME BASTA" },
  { "number": "312", "name": "SE, DA VIDA, AS VAGAS PROCEL0SAS SÃO" },
  { "number": "313", "name": "O QUE HABITA NO ABRIGO DE DEUS" },
  { "number": "314", "name": "QUE IMPORTA" },
  { "number": "315", "name": "SE EM PROFUNDO ABISMO TE ENCONTRAS" },
  { "number": "316", "name": "A VIDA NO MUNDO É CRUEL" },
  { "number": "317", "name": "QUANDO VEM NOS OLHOS UMA LÁGRIMA" },
  { "number": "318", "name": "QUANDO A ANGÚSTIA VEM" },
  { "number": "319", "name": "MAIS PERTO QUERO ESTAR" },
  { "number": "320", "name": "BOM É O SENHOR" },
  { "number": "321", "name": "QUÃO BONDOSO AMIGO É CRISTO" },
  { "number": "322", "name": "HÁ UM AMIGO SEMPRE JUNTO" },
  { "number": "323", "name": "DEUS ESTÁ PRESENTE SEMPRE PRONTO A NOS AJUDAR" },
  { "number": "324", "name": "EU SOU POBRE E NECESSITADO" },
  { "number": "325", "name": "SE HOJE ESCUTARES" },
  { "number": "326", "name": "EU NÃO SABERIA CAMINHAR" },
  { "number": "327", "name": "DEUS É CONTIGO" },
  { "number": "328", "name": "CONSOLAI, CONSOLAI O MEU POVO" },
  { "number": "329", "name": "ATUA EM NOSSO MEIO" },
  { "number": "330", "name": "EIS AÍ O DIA ACEITÁVEL" },
  { "number": "331", "name": "SE DEUS É POR NÓS" },
  { "number": "332", "name": "O REI E EU" },
  { "number": "333", "name": "SE TE ENCONTRARES TRISTE" },
  { "number": "334", "name": "DEUS CUIDA DE TI" },
  { "number": "335", "name": "NÃO DESANIMES! DEUS PROVERÁ" },
  { "number": "336", "name": "HÁ ALGUÉM QUE CUIDA DE TI" },
  { "number": "337", "name": "O MESMO DEUS" },
  { "number": "338", "name": "DIVINO COMPANHEIRO" },
  { "number": "339", "name": "PARA OS MONTES OLHAREI" },
  { "number": "340", "name": "DEUS TE GUARDARÁ" },
  { "number": "341", "name": "QUE CONSOLAÇÃO" },
  { "number": "342", "name": "ROCHA MINHA" },
  { "number": "343", "name": "OS QUE CONFiam NO SENHOR" },
  { "number": "344", "name": "CONFIO EM DEUS" },
  { "number": "345", "name": "EM NADA PONHO A MINHA FÉ" },
  { "number": "346", "name": "SE A FÉ POR VEZES FALTA" },
  { "number": "347", "name": "FIRME NAS PROMESSAS" },
  { "number": "348", "name": "ESPERA NO SENHOR, ANIMA-TE" },
  { "number": "349", "name": "SE NÃO FOSSE O SENHOR" },
  { "number": "350", "name": "FAZ-ME INABALÁVEL" },
  { "number": "351", "name": "TU ÉS MEU REI" },
  { "number": "352", "name": "QUERES NESTE MUNDO SER UM VENCEDOR?" },
  { "number": "353", "name": "DEIXA-ME CHORAR" },
  { "number": "354", "name": "CRISTO ME DARÁ" },
  { "number": "355", "name": "VENCER, VENCER" },
  { "number": "356", "name": "O SENHOR É O MEU PASTOR (REFRIGERA A MINHA ALMA)" },
  { "number": "357", "name": "O SENHOR É O MEU PASTOR (BONDADE E MISERICÓRDIA)" },
  { "number": "358", "name": "O SENHOR É O MEU PASTOR (SL 23)" },
  { "number": "359", "name": "DEUS É NOSSO AMPARO, NOSSA FORTALEZA" },
  { "number": "360", "name": "ROCHEDO FORTE É O SENHOR" },
  { "number": "361", "name": "NÃO HÁ DEUS ACIMA DO SENHOR" },
  { "number": "362", "name": "DEUS PROVERÁ" },
  { "number": "363", "name": "QUANDO AS LUTAS ME CERCAM" },
  { "number": "364", "name": "DÁ-ME MAIS FÉ" },
  { "number": "365", "name": "NÃO TEMAS, POIS TE ESCOLHI (QUANDO PELAS ÁGUAS)" },
  { "number": "366", "name": "AS LÁGRIMAS FALAM, JESUS TE ESCUTA" },
  { "number": "367", "name": "SE AS LUTAS DA VIDA" },
  { "number": "368", "name": "ESFORÇA-TE, TEM BOM ÂNIMO" },
  { "number": "369", "name": "QUANDO MAIS NINGUÉM TE COMPREENDE" },
  { "number": "370", "name": "JESUS É A ROCHA INABALÁVEL" },
  { "number": "371", "name": "TODA PROMESSA" },
  { "number": "372", "name": "MUITOS SÃO OS QUE CONFiam" },
  { "number": "373", "name": "SE UM DIA DEUS PROMETEU" },
  { "number": "374", "name": "QUERO TOCAR EM TUAS VESTES, SENHOR" },
  { "number": "375", "name": "OS SEGREDOS DO TEU CORAÇÃO" },
  { "number": "376", "name": "O SENHOR TE GUIARÁ" },
  { "number": "377", "name": "DEUS É MINHA ROCHA" },
  { "number": "378", "name": "CONFIA E ORA" },
  { "number": "379", "name": "ALGEMADO POR UM PESO" },
  { "number": "380", "name": "POSSO SENTIR O SEU TOQUE EM MIM (GLORIFICA)" },
  { "number": "381", "name": "MEU DEUS VENCE BATALHAS" },
  { "number": "382", "name": "JÁ CHEGUEI ATÉ AQUI (VITÓRIAS)" },
  { "number": "383", "name": "LÁ ONDE EU NÃO POSSO VER (A ORAÇÃO)" },
  { "number": "384", "name": "BEM SEI QUE TUDO PODES" },
  { "number": "385", "name": "QUÃO DIFÍCIL É, SENHOR (FAZE-ME UM VENCEDOR)" },
  { "number": "386", "name": "QUAL O ADORNO DESTA VIDA?" },
  { "number": "387", "name": "SONDA-ME, Ó DEUS" },
  { "number": "388", "name": "SÓ TU ÉS, SENHOR" },
  { "number": "389", "name": "SENHOR, O QUE É A NOSSA VIDA?" },
  { "number": "390", "name": "CANTAREI A MISERICÓRDIA" },
  { "number": "391", "name": "CANTAREI A BONDADE E A JUSTIÇA" },
  { "number": "392", "name": "EU SÓ QUERO SER, SENHOR" },
  { "number": "393", "name": "QUERO SER FIEL AO MEU SENHOR" },
  { "number": "394", "name": "UMA VOZ ME DISSE LÁ DO CÉU" },
  { "number": "395", "name": "FALA, JESUS QUERIDO" },
  { "number": "396", "name": "ABBA PAI" },
  { "number": "397", "name": "HÁ UMA LUZ A BRILHAR" },
  { "number": "398", "name": "ENTREI NO TEMPO DE DEUS" },
  { "number": "399", "name": "QUAL MADEIRA" },
  { "number": "400", "name": "EU QUERO SER, SENHOR AMADO" },
  { "number": "401", "name": "COMO TU QUERES" },
  { "number": "402", "name": "A LEI DO SENHOR É PERFEITA" },
  { "number": "403", "name": "AQUELE QUE TEM OS MEUS MANDAMENTOS" },
  { "number": "404", "name": "JESUS, QUERO AMAR-TE" },
  { "number": "405", "name": "AMO AO SENHOR DE TODO O MEU CORAÇÃO" },
  { "number": "406", "name": "JESUS, O QUE EU MAIS QUERO NO MUNDO" },
  { "number": "407", "name": "EU VI O SENHOR" },
  { "number": "408", "name": "EIS QUE SURGE UM POVO FORTE" },
  { "number": "409", "name": "EIS MARCHAMOS PARA AQUELE BOM PAÍS" },
  { "number": "410", "name": "UM PENDÃO REAL VOS ENTREGOU O REI" },
  { "number": "411", "name": "O SENHOR DA CEIFA ESTÁ CHAMANDO" },
  { "number": "412", "name": "SOU FORASTEIRO AQUI" },
  { "number": "413", "name": "OUVI, Ó CÉUS, E FALAREI" },
  { "number": "414", "name": "MEU DEUS, MEU BOM PASTOR" },
  { "number": "415", "name": "QUERO SER UM VASO DE BÊNÇÃO" },
  { "number": "416", "name": "PELAS PRAIAS GALILÉIAS VEM JESUS" },
  { "number": "417", "name": "MINHA DEDICAÇÃO" },
  { "number": "418", "name": "HÁ UM POVO QUE TE ADORA" },
  { "number": "419", "name": "HÁ UMA OBRA QUE DEUS QUER FAZER" },
  { "number": "420", "name": "SOMOS TEU POVO E QUEREMOS" },
  { "number": "421", "name": "A OBRA DO SENHOR É PERFEITA" },
  { "number": "422", "name": "A MINHA HERANÇA" },
  { "number": "423", "name": "Ó PASTOR DE ISRAEL" },
  { "number": "424", "name": "O MEU AMADO DESCEU AO SEU JARDIM" },
  { "number": "425", "name": "QUE VISTA AMÁVEL É" },
  { "number": "426", "name": "UM CORPO SÓ, UM SÓ ESPÍRITO" },
  { "number": "427", "name": "OH! QUÃO BOM E QUÃO SUAVE É" },
  { "number": "428", "name": "VEM, Ó CRISTO, ENCHER MEU CÁLICE" },
  { "number": "429", "name": "ÉS O PÃO DA VIDA" },
  { "number": "430", "name": "COMO CRISTO ENSINOU" },
  { "number": "431", "name": "CRISTO JÁ NOS PREPAROU" },
  { "number": "432", "name": "OUÇO A VOZ DO MEU AMADO ME CHAMAR" },
  { "number": "433", "name": "TOMAI AGORA O PÃO" },
  { "number": "434", "name": "HÁ UM DOCE ESPÍRITO AQUI" },
  { "number": "435", "name": "FLUIRÁ COMO UM RIO" },
  { "number": "436", "name": "ESPÍRITO DO TRINO DEUS" },
  { "number": "437", "name": "VEM SOBRE MIM, ESPÍRITO DE DEUS" },
  { "number": "438", "name": "O ESPÍRITO DO SENHOR ESTÁ SENDO DERRAMADO" },
  { "number": "439", "name": "Ó VEM DERRAMAR" },
  { "number": "440", "name": "DERRAMAREI MEU ESPÍRITO" },
  { "number": "441", "name": "ESPÍRITO SANTO, Ó CONSOLADOR" },
  { "number": "442", "name": "MAIS DO TEU SANTO ESPÍRITO (PORÇÃO DOBRADA)" },
  { "number": "443", "name": "HÁ UM RIO DE ÁGUAS VIVAS" },
  { "number": "444", "name": "DESEJEI ARDENTEMENTE" },
  { "number": "445", "name": "DIRIGE-ME, SENHOR" },
  { "number": "446", "name": "A TUA PALAVRA" },
  { "number": "447", "name": "SENHOR, GUIA-NOS" },
  { "number": "448", "name": "SENHOR, EU QUERO SERVIR-TE" },
  { "number": "449", "name": "A MINHA VIDA ENTREGO" },
  { "number": "450", "name": "A TUA JUSTIÇA" },
  { "number": "451", "name": "NO SERVIÇO DO MEU REI EU SOU FELIZ" },
  { "number": "452", "name": "QUERO QUE ME TOQUES, SENHOR" },
  { "number": "453", "name": "QUANDO DOBRO OS MEUS JOELHOS EM ORAÇÃO" },
  { "number": "454", "name": "SENHOR, MEU DEUS, O QUE DIREI DE TI? (SAÚDE ESPIRITUAL)" },
  { "number": "455", "name": "QUANTO MAIS EU TE CONHEÇO (CAMINHO FELIZ)" },
  { "number": "456", "name": "CHUVAS DE BÊNÇÃOS TEREMOS" },
  { "number": "457", "name": "INSTRUMENTO EM TUAS MÃOS" },
  { "number": "458", "name": "Ó CRISTO! PÃO DA VIDA" },
  { "number": "459", "name": "É TEMPO, É TEMPO (MARCHAR AVANTE!)" },
  { "number": "460", "name": "Ó JESUS! Ó VERA PÁSCOA" },
  { "number": "461", "name": "TU, Ó SENHOR, TU ÉS TÃO PURO DE OLHOS (AVIVA A TUA OBRA)" },
  { "number": "462", "name": "QUANTOS FIÉIS, SENHOR" },
  { "number": "463", "name": "VEM, SENHOR, VISITA TUA VINHA" },
  { "number": "464", "name": "TU QUE SOBRE A AMARGA CRUZ" },
  { "number": "465", "name": "O ESTANDARTE DESTA IGREJA" },
  { "number": "466", "name": "EIS O ESTANDARTE" },
  { "number": "467", "name": "OS GUERREIROS SE PREPARAM" },
  { "number": "468", "name": "HÁ TANTA TERRA" },
  { "number": "469", "name": "CASTELO FORTE" },
  { "number": "470", "name": "NO GETSÊMANI" },
  { "number": "471", "name": "VEM, ESPÍRITO DE DEUS" },
  { "number": "472", "name": "VINDE, CANTAI E ENTOAI LOUVORES A JESUS" },
  { "number": "473", "name": "MINHA PORÇÃO" },
  { "number": "474", "name": "QUEM SOU EU, SENHOR?" },
  { "number": "475", "name": "AINDA UMA VEZ (AGEU)" },
  { "number": "476", "name": "ESTA OBRA É DE DEUS" },
  { "number": "477", "name": "SEMPRE VOU LEMBRAR" },
  { "number": "478", "name": "VI UM NOVO CÉU" },
  { "number": "479", "name": "QUEM ME DERA" },
  { "number": "480", "name": "EU ESPERO, ANSIOSO, POR MEU DEUS" },
  { "number": "481", "name": "ASSIM COMO A NOITE ESPERA PELO DIA" },
  { "number": "482", "name": "OS SINAIS DO FIM SE CUMPREM" },
  { "number": "483", "name": "CHEGOU O TEMPO DE PENSAR" },
  { "number": "484", "name": "TEMEI A DEUS" },
  { "number": "485", "name": "SETE CASTIÇAIS" },
  { "number": "486", "name": "DO NORTE VEM O ÁUREO ESPLENDOR" },
  { "number": "487", "name": "VIGIAI E SEMPRE ORAI, Ó CRENTES" },
  { "number": "488", "name": "CERTA VEZ, AO ORAR" },
  { "number": "489", "name": "EM BREVE ESCUTAREI" },
  { "number": "490", "name": "ELE VOLTARÁ PRA BUSCAR A SUA IGREJA" },
  { "number": "491", "name": "ELE UM DIA VOLTARÁ" },
  { "number": "492", "name": "ELE VOLTARÁ, SIM, ELE VOLTARÁ" },
  { "number": "493", "name": "COMO FOI PARA O CÉU, JESUS CRISTO HÁ DE VIR" },
  { "number": "494", "name": "NÃO SEI QUANDO CRISTO JESUS HÁ DE VIR" },
  { "number": "495", "name": "O QUE HÁ DE VIR, VIRÁ" },
  { "number": "496", "name": "NÃO VAI TARDAR" },
  { "number": "497", "name": "JESUS, SIM, VEM, DO CÉU EM GLÓRIA ELE VEM" },
  { "number": "498", "name": "CRISTO VEM ME BUSCAR" },
  { "number": "499", "name": "OUÇO UMA VOZ TÃO SUAVE" },
  { "number": "500", "name": "SEI QUE O SENHOR" },
  { "number": "501", "name": "O ESPÍRITO DE DEUS FALA À SUA IGREJA" },
  { "number": "502", "name": "QUANDO LÁ DO CÉU DESCENDO" },
  { "number": "503", "name": "TENHO SAUDADES DE JESUS, MEU MESTRE" },
  { "number": "504", "name": "EU SEI QUE JESUS" },
  { "number": "505", "name": "OS SEUS CABELOS BRANCOS" },
  { "number": "506", "name": "TU QUE ESTÁS ASSENTADO" },
  { "number": "507", "name": "O SOL ESCURECERÁ" },
  { "number": "508", "name": "BREVE NO CÉU JESUS HÁ DE APARECER" },
  { "number": "509", "name": "EM BREVE, MUI BREVE" },
  { "number": "510", "name": "ALERTA POVO, ESTÁ CHEGANDO A NOSSA HORA" },
  { "number": "511", "name": "JESUS CRISTO VOLTARÁ COM SEU GRANDE ESPLENDOR" },
  { "number": "512", "name": "O MEU AMADO FALA E ME DIZ" },
  { "number": "513", "name": "QUEM É ESTA QUE APARECE" },
  { "number": "514", "name": "ESTA É A VOZ, A VOZ DO MEU AMADO" },
  { "number": "515", "name": "QUANDO A ÚLTIMA TROMBETA ECOAR" },
  { "number": "516", "name": "QUANDO A ANGELICAL TROMBETA" },
  { "number": "517", "name": "JÁ NÃO TARDA O AMANHECER" },
  { "number": "518", "name": "NÃO TEREI MAIS TRISTEZAS" },
  { "number": "519", "name": "UM NOVO LAR ME ESPERA" },
  { "number": "520", "name": "NO TRONO DA CIDADE DE DEUS" },
  { "number": "521", "name": "AO CHEGAR AO CÉU GOZO EU TEREI" },
  { "number": "522", "name": "EXISTE UM LAR" },
  { "number": "523", "name": "LÁ NO CÉU OS ANJOS CANTAM" },
  { "number": "524", "name": "SE EU ESTIVESSE NA ALVORADA" },
  { "number": "525", "name": "HÁ UM LINDO PAÍS" },
  { "number": "526", "name": "LINDO! LINDO! LINDO!" },
  { "number": "527", "name": "REGOZIJAI-VOS" },
  { "number": "528", "name": "EU AVISTO UMA TERRA FELIZ" },
  { "number": "529", "name": "EU OUVI DA FORMOSA CIDADE" },
  { "number": "530", "name": "OH! QUE SAUDOSA LEMBRANÇA" },
  { "number": "531", "name": "JERUSALÉM, JERUSALÉM" },
  { "number": "532", "name": "QUANDO O MUNDO AQUI DEIXAR" },
  { "number": "533", "name": "MINHA ALMA, POIS, ALEGRE CANTA" },
  { "number": "534", "name": "BREVE VOLTARÁ O MESSIAS" },
  { "number": "535", "name": "ALÉM DO CÉU AZUL" },
  { "number": "536", "name": "FINDA A LIDA TERREAL" },
  { "number": "537", "name": "QUANDO O JORDÃO PASSARMOS UNIDOS" },
  { "number": "538", "name": "HÁ UM LUGAR PRA MIM" },
  { "number": "539", "name": "JUNTO AO TRONO DE DEUS, PREPARADO" },
  { "number": "540", "name": "OH! PENSAI NESSE LAR LÁ DO CÉU" },
  { "number": "541", "name": "ARREBATADO FUI NO DIA DO SENHOR" },
  { "number": "542", "name": "AO LADO DE JESUS EU QUERO ESTAR" },
  { "number": "543", "name": "AO LADO DE DEUS" },
  { "number": "544", "name": "EM BREVE O DIA CHEGARÁ" },
  { "number": "545", "name": "JESUS ESTÁ ÀS PORTAS" },
  { "number": "546", "name": "OH! QUANTO ALMEJO ESTAR" },
  { "number": "547", "name": "Ó VEM LOGO, JESUS" },
  { "number": "548", "name": "NAS LINDAS MORADAS" },
  { "number": "549", "name": "MARAVILHOSO SERÁ" },
  { "number": "550", "name": "CANTAI, Ó IGREJA" },
  { "number": "551", "name": "TENHO LIDO DA BELA CIDADE (A BELA CIDADE)" },
  { "number": "552", "name": "PÁTRIA MINHA" },
  { "number": "553", "name": "VEM! MARANATA, JESUS VEM!" },
  { "number": "554", "name": "JERUSALÉM (SUAS RUAS DE OURO)" },
  { "number": "555", "name": "DA LINDA PÁTRIA" },
  { "number": "556", "name": "NA NOVA JERUSALÉM IREI MORAR" },
  { "number": "557", "name": "ESTE MUNDO JAMAIS PODE ME SEPARAR" },
  { "number": "558", "name": "VEM, JESUS CRISTO JÁ VEM" },
  { "number": "559", "name": "A ÚLTIMA TROMBETA SOARÁ" },
  { "number": "560", "name": "EIS QUE ESTOU À PORTA E BATO" },
  { "number": "561", "name": "OUVI COMO QUE A VOZ DE UMA GRANDE MULTIDÃO" },
  { "number": "562", "name": "QUANDO MEU TEMPO DE LUTAS PASSAR" },
  { "number": "563", "name": "NÃO SE TURBEM OS VOSSOS CORAÇÕES" },
  { "number": "564", "name": "DISPÕE-TE, RESPLANDECE" },
  { "number": "565", "name": "LÁ ESTÁ O MEU TESOURO" },
  { "number": "566", "name": "O SENHOR É O MEU PASTOR (MARANATA, JESUS VEM)" },
  { "number": "567", "name": "QUANDO SERÁ O GRANDE DIA" },
  { "number": "568", "name": "SENHOR, QUEM SÃO AQUELES" },
  { "number": "569", "name": "JESUS VEM! VEM NOS BUSCAR!" },
  { "number": "570", "name": "JÁ REFULGE A GLÓRIA ETERNA (VENCENDO VEM JESUS!)" },
  { "number": "571", "name": "O GRANDE DIA ESTÁ CHEGANDO" },
  { "number": "572", "name": "CHEGUEMOS AO ALTAR DE DEUS" },
  { "number": "573", "name": "COMO É BOM TE ADORAR" },
  { "number": "574", "name": "ADORAREI" },
  { "number": "575", "name": "TE ADORAMOS" },
  { "number": "576", "name": "REUNIMO-NOS AQUI PRA TE ADORAR" },
  { "number": "577", "name": "GLÓRIA E ALELUIA" },
  { "number": "578", "name": "HOJE O SENHOR DERRAMOU" },
  { "number": "579", "name": "SENHOR, EU NEM SEI CONTAR" },
  { "number": "580", "name": "NOS PROSTREMOS AOS SEUS PÉS" },
  { "number": "581", "name": "PAI DE AMOR, GOSTO TANTO DE TI" },
  { "number": "582", "name": "CANTAREI AO AMOR DOS AMORES" },
  { "number": "583", "name": "Ó GRANDE DEUS" },
  { "number": "584", "name": "EU TE AMO, MEU JESUS" },
  { "number": "585", "name": "FONTE DA VIDA" },
  { "number": "586", "name": "Ó PROFUNDIDADE DAS RIQUEZAS" },
  { "number": "587", "name": "Ó JESUS, EXALTAR-TE-EI" },
  { "number": "588", "name": "HÁ UM NOME QUE RELUZ" },
  { "number": "589", "name": "JESUS TÃO BELO" },
  { "number": "590", "name": "AO CORDEIRO" },
  { "number": "591", "name": "GLÓRIA PRA SEMPRE AO CORDEIRO DE DEUS" },
  { "number": "592", "name": "ALELUIA! MUITAS VOZES DE ANJOS" },
  { "number": "593", "name": "A CRISTO COROAI" },
  { "number": "594", "name": "NA EXPRESSÃO DESTE LOUVOR" },
  { "number": "595", "name": "MAJESTADE, GLÓRIA E MAJESTADE" },
  { "number": "596", "name": "ÉS MAJESTADE" },
  { "number": "597", "name": "CANTAREI, CANTAREI HOSANA (VIVA O REI)" },
  { "number": "598", "name": "HÁ UM SÓ QUE É DIGNO" },
  { "number": "599", "name": "JESUS, TE ENTRONIZAMOS AQUI ENTRE NÓS" },
  { "number": "600", "name": "JESUS, TE ENTRONIZAMOS" },
  { "number": "601", "name": "AO QUE ESTÁ NO TRONO" },
  { "number": "602", "name": "SANTO É O QUE ESTÁ NO TRONO" },
  { "number": "603", "name": "LOUVAREI AO MEU SENHOR" },
  { "number": "604", "name": "O MEU LOUVOR É FRUTO" },
  { "number": "605", "name": "NOSSO DEUS É SOBERANO" },
  { "number": "606", "name": "O CRIADOR DO UNIVERSO" },
  { "number": "607", "name": "A DEUS SEJA O LOUVOR" },
  { "number": "608", "name": "DEUS DOS EXÉRCITOS DE ISRAEL" },
  { "number": "609", "name": "SENHOR, MEU DEUS, QUANDO EU MARAVILHADO" },
  { "number": "610", "name": "SANTO! SANTO! SANTO! DEUS ONIPOTENTE!" },
  { "number": "611", "name": "JESUS, DEUS SANTO, SANTO, SANTO!" },
  { "number": "612", "name": "SANTO, SANTO, SANTO, Ó DEUS DE GLÓRIA E PODER" },
  { "number": "613", "name": "DAI GLÓRIA A DEUS" },
  { "number": "614", "name": "A DEUS DEMOS GLÓRIA" },
  { "number": "615", "name": "LOUVOR E GLÓRIA" },
  { "number": "616", "name": "AO DEUS DE AMOR E DE IMENSA BONDADE" },
  { "number": "617", "name": "O MEU CORAÇÃO SE REGOZIJA NO SENHOR" },
  { "number": "618", "name": "CANTAREI AO MEU SENHOR ENQUANTO EU VIVER" },
  { "number": "619", "name": "VEM, DERRAMA A PAZ" },
  { "number": "620", "name": "ESTAMOS AQUI, Ó DEUS" },
  { "number": "621", "name": "ADORAR-TE" },
  { "number": "622", "name": "A BELEZA DA TUA SANTIDADE" },
  { "number": "623", "name": "EU QUERO CANTAR DE GOZO E DE PAZ" },
  { "number": "624", "name": "A MINH'ALMA ENGRANDECE" },
  { "number": "625", "name": "DIGNO É JESUS" },
  { "number": "626", "name": "OH! CONTEMPLAI" },
  { "number": "627", "name": "NÓS TE ADORAMOS, SENHOR" },
  { "number": "628", "name": "SANTO É SEU NOME" },
  { "number": "629", "name": "QUE ALEGRIA" },
  { "number": "630", "name": "SUDAI O NOME DE JESUS" },
  { "number": "631", "name": "SÊ EXALTADO, Ó DEUS" },
  { "number": "632", "name": "MUITOS ANJOS LOUVAM" },
  { "number": "633", "name": "TE EXALTAREMOS" },
  { "number": "634", "name": "GLORIOSO ÉS, JESUS" },
  { "number": "635", "name": "ENTRONIZADO ESTÁ ENTRE AS NAÇÕES" },
  { "number": "636", "name": "LOUVAI A JESUS" },
  { "number": "637", "name": "TODA A TERRA TE EXALTA" },
  { "number": "638", "name": "JESUS VEIO E SALVOU-ME" },
  { "number": "639", "name": "MOTIVOS TENHO PRA LOUVAR-TE" },
  { "number": "640", "name": "MEU LOUVOR É SÓ PRA TI" },
  { "number": "641", "name": "A LUZ DO MUNDO" },
  { "number": "642", "name": "EM NOSSOS LÁBIOS" },
  { "number": "643", "name": "TODO LOUVOR SEJA DADO A DEUS" },
  { "number": "644", "name": "LOUVAMOS-TE, Ó DEUS" },
  { "number": "645", "name": "COROAI" },
  { "number": "646", "name": "AGRADECIDOS SOMOS A TI" },
  { "number": "647", "name": "SANTO, SANTO, SANTO É O SENHOR" },
  { "number": "648", "name": "O SENHOR É O MEU PASTOR (MINH'ALMA CANTARÁ)" },
  { "number": "649", "name": "TE LOUVAMOS, SENHOR" },
  { "number": "650", "name": "Ó VINDE E ADOREMOS" },
  { "number": "651", "name": "AMO AO SENHOR" },
  { "number": "652", "name": "LEVANTAI-VOS, Ó PORTAIS ETERNOS" },
  { "number": "653", "name": "ALELUIA (SL 113)" },
  { "number": "654", "name": "GRANDE É O SENHOR E MUI DIGNO DE SER LOUVADO" },
  { "number": "655", "name": "LOUVAI, SERVOS DO SENHOR" },
  { "number": "656", "name": "GRANDE É O SENHOR" },
  { "number": "657", "name": "OS CÉUS PROCLAMAM" },
  { "number": "658", "name": "MEDITAREI NAS MARAVILHAS DO SENHOR" },
  { "number": "659", "name": "CELEBRAI COM JÚBILO AO SENHOR" },
  { "number": "660", "name": "O MEU CORAÇÃO" },
  { "number": "661", "name": "ÉS O MAIS FORMOSO, JESUS" },
  { "number": "662", "name": "ONIPOTENTE DEUS" },
  { "number": "663", "name": "LOUVAI AO SENHOR TODAS AS NAÇÕES" },
  { "number": "664", "name": "QUÃO AMÁVEIS SÃO" },
  { "number": "665", "name": "BENDEZEI AO SENHOR" },
  { "number": "666", "name": "TAL QUAL ESTOU" },
  { "number": "667", "name": "JUSTO ÉS, SENHOR" },
  { "number": "668", "name": "UM POBRE CEGO" },
  { "number": "669", "name": "DEUS DOS ANTIGOS" },
  { "number": "670", "name": "SE PAZ, A MAIS DOCE" },
  { "number": "671", "name": "OUVE, POIS, ISRAEL" },
  { "number": "672", "name": "MEU SERVO, NÃO TEMAS" },
  { "number": "673", "name": "Ó PAI, EU QUERIA TANTO VER (AUTOR DA MINHA FÉ)" },
  { "number": "674", "name": "EU NÃO SEI QUAL SERÁ MEU LOUVOR" },
  { "number": "675", "name": "NA ETERNIDADE" },
  { "number": "676", "name": "Ó VINDE ADORAR" },
  { "number": "677", "name": "A TI, QUE HABITAS ENTRE OS QUERUBINS" },
  { "number": "678", "name": "TUA GLÓRIA ENCHE TODA A TERRA" },
  { "number": "679", "name": "EIS A ESCRAVA RESGATADA" },
  { "number": "680", "name": "TEU NOME É PRA MIM, SENHOR" },
  { "number": "681", "name": "NOSSO LOUVOR" },
  { "number": "682", "name": "A JESUS SEJA DADA TODA GLÓRIA" },
  { "number": "683", "name": "JESUS CRISTO VOLTARÁ" },
  { "number": "684", "name": "ELE É O REI DOS REIS" },
  { "number": "685", "name": "PERFEITO AMOR EU CONHECI" },
  { "number": "686", "name": "QUANDO JESUS PROVOU O SEU AMOR POR MIM" },
  { "number": "687", "name": "QUEM É COMO TU?" },
  { "number": "688", "name": "CRISTO JÁ RESSUSCITOU" },
  { "number": "689", "name": "AMOR, QUE POR AMOR DESCESTE!" },
  { "number": "690", "name": "DA IGREJA O FUNDAMENTO É CRISTO (A PEDRA FUNDAMENTAL)" },
  { "number": "691", "name": "AO DEUS DE ABRAÃO" },
  { "number": "692", "name": "COMIGO HABITA, Ó DEUS!" },
  { "number": "693", "name": "DORMINDO NO MEU LEITO (JERUSALÉM, CIDADE SANTA)" },
  { "number": "694", "name": "JERUSALÉM ETERNA" },
  { "number": "695", "name": "JERUSALÉM EXCELSA" },
  { "number": "696", "name": "NA TERRA ABENÇOADA" },
  { "number": "697", "name": "OUVI O SALVADOR DIZER" },
  { "number": "698", "name": "TUA, Ó DEUS, É TODA A GRANDEZA" },
  { "number": "699", "name": "QUE GRANDE REUNIÃO CONVOCADA ALI (JESUS DE NAZARÉ)" },
  { "number": "700", "name": "ESTEVÃO AVISTOU (EU TAMBÉM QUERO VER)" },
  { "number": "701", "name": "AS TUAS MÃOS DIRIGEM MEU DESTINO" },
  { "number": "702", "name": "OS CÉUS EM BREVE SE ABRIRÃO" },
  { "number": "703", "name": "SERÁ DE MANHÃ" },
  { "number": "704", "name": "SENHOR, SE ESTIVESSES AQUI (LÁZARO)" },
  { "number": "705", "name": "GRANDES SÃO, SENHOR, OS TEUS FEITOS (GRATIDÃO)" },
  { "number": "706", "name": "DESTE MUNDO ESCRAVO FUI (GRANDES COISAS FEZ O SENHOR POR NÓS)" },
  { "number": "707", "name": "EU CONFIO EM TI, SENHOR" },
  { "number": "708", "name": "OUVI NO CÉU (BODAS DO CORDEIRO)" },
  { "number": "709", "name": "RESPLANDECE, Ó JERUSALÉM" },
  { "number": "710", "name": "O MEU VIVER É CRISTO" },
  { "number": "711", "name": "TUA GRAÇA ME BASTA, Ó SENHOR" },
  { "number": "712", "name": "AO FINDAR O LABOR DESTA VIDA (A ÚLTIMA HORA)" },
  { "number": "713", "name": "CAREÇO DE JESUS" },
  { "number": "714", "name": "COM TUA MÃO SEGURA BEM A MINHA (AMPARO DIVINO)" },
  { "number": "715", "name": "DEUS VOS GUARDE PELO SEU PODER" },
  { "number": "716", "name": "ENQUANTO, Ó SALVADOR, TEU LIVRO LER" },
  { "number": "717", "name": "A TERRA SEMEAMOS" },
  { "number": "718", "name": "GUIA, Ó CRISTO, MINHA NAU" },
  { "number": "719", "name": "AVANTE, AVANTE, Ó CRENTES" },
  { "number": "720", "name": "AS GRUTAS, AS ROCHAS IMENSAS (UM HINO AO SENHOR)" },
  { "number": "721", "name": "PROCLAMAI A TODO O MUNDO QUE O SENHOR É REI" },
  { "number": "722", "name": "A DEUS, SUPREMO BENFEITOR" },
  { "number": "723", "name": "CRISTO PODE HOJE VIR (OH! DIA ALEGRE!)" },
  { "number": "724", "name": "EIS OS MILHÕES" },
  { "number": "725", "name": "EU PERDIDO PECADOR" },
  { "number": "726", "name": "QUANDO A TEMPESTADE RUGE" },
  { "number": "727", "name": "EIS QUE ABRO A PORTA" },
  { "number": "728", "name": "NOSSA GRATIDÃO" },
  { "number": "729", "name": "OS TEUS ANJOS TE EXALTAM" },
  { "number": "730", "name": "SÓ TU NOS FAZES VENCEDORES" },
  { "number": "731", "name": "SEQUÊNCIA DE LOUVORES Nº 1" },
  { "number": "732", "name": "SEQUÊNCIA DE LOUVORES Nº 2" },
  { "number": "733", "name": "SEQUÊNCIA DE LOUVORES Nº 3" },
  { "number": "734", "name": "ÁVIDA DE MINH'ALMA" },
  { "number": "735", "name": "SEU NOME É JESUS" },
  { "number": "736", "name": "CRISTO É A RESPOSTA" },
  { "number": "737", "name": "SE ESTÁS CANSADO" },
  { "number": "738", "name": "GLÓRIA, GLÓRIA" },
  { "number": "739", "name": "EU TENHO UM TESOURO" },
  { "number": "740", "name": "EU TENHO UM DEUS MUI, MUI, MUI GRANDE" },
  { "number": "741", "name": "NÃO HÁ DEUS TÃO GRANDE COMO TU" },
  { "number": "742", "name": "NO CÉU HÁ JANELAS ABERTAS" },
  { "number": "743", "name": "VENCEDOR SEREI" },
  { "number": "744", "name": "VITÓRIA DEUS DARÁ A MIM, EU SEI" },
  { "number": "745", "name": "É DEUS QUEM NOS TEM DADO A VITÓRIA" },
  { "number": "746", "name": "JESUS É O AMIGO MELHOR" },
  { "number": "747", "name": "SENHOR, MANDA PODER" },
  { "number": "748", "name": "QUE CALOR É ESTE EM VOLTA DO ALTAR?" },
  { "number": "749", "name": "MANDA FOGO, SENHOR" },
  { "number": "750", "name": "DEIXA A GLÓRIA DE DEUS BRILHAR" },
  { "number": "751", "name": "EU LOUVAREI, EU LOUVAREI" },
  { "number": "752", "name": "ESTOU ALEGRE" },
  { "number": "753", "name": "A NOIVA ÉS IGREJA" },
  { "number": "754", "name": "EU VEREI A ÁRVORE DA VIDA" },
  { "number": "755", "name": "SOMENTE PELA FÉ" },
  { "number": "756", "name": "QUEM CANTAR AQUI SE ALEGRARÁ" },
  { "number": "757", "name": "COMO ACONTECEU EM JERUSALÉM" },
  { "number": "758", "name": "ESTA ALEGRIA NÃO VAI MAIS SAIR" },
  { "number": "759", "name": "NUNCA MAIS, NUNCA MAIS" },
  { "number": "760", "name": "DO CÉU VIRÁ" },
  { "number": "761", "name": "CADA PASSO QUE DÁS" },
  { "number": "762", "name": "O CÉU É UM LUGAR MARAVILHOSO" },
  { "number": "763", "name": "JESUS É TUDO PRA MIM" },
  { "number": "764", "name": "NÓS VAMOS LÁ, IRMÃOS" },
  { "number": "765", "name": "LÁ NO CÉU TODOS CANTAM ALELUIA!" },
  { "number": "766", "name": "NO DIA DA GRANDE GLÓRIA" },
  { "number": "767", "name": "CONTA PRA JESUS ONDE É A TUA DOR" },
  { "number": "768", "name": "A VITÓRIA DESTA IGREJA É ORAÇÃO" },
  { "number": "769", "name": "O GRANDE RELÓGIO" },
  { "number": "770", "name": "POR QUE DEIXAR QUE AS ÂNSIAS" },
  { "number": "771", "name": "CAMINHANDO VOU PARA CANAÃ" },
  { "number": "772", "name": "CADA DIA ME DIRIGE" },
  { "number": "773", "name": "ABRA A PORTA, VENHA VER" },
  { "number": "774", "name": "CHEGADO À CRUZ DO MEU SALVADOR" },
  { "number": "775", "name": "SUBINDO PARA O CÉU EU VOU" },
  { "number": "776", "name": "CERTA VEZ EU ORANDO" },
  { "number": "777", "name": "COMO AS ÁGUAS" },
  { "number": "778", "name": "DEUS ESTÁ AQUI" },
  { "number": "779", "name": "ABRE A PORTA DO TEU CORAÇÃO" },
  { "number": "780", "name": "CANTAREI, CANTAREI AS MISERICÓRDIAS" },
  { "number": "781", "name": "SÓ O PODER DE DEUS" },
  { "number": "782", "name": "TENHO NOVA VIDA" },
  { "number": "783", "name": "FELIZ, FELIZ EU SOU" },
  { "number": "784", "name": "CANTAI AO SENHOR UM CÂNTICO NOVO" },
  { "number": "785", "name": "ESTOU CONFIANDO" },
  { "number": "786", "name": "QUE AS PALAVRAS DA MINHA BOCA" },
  { "number": "787", "name": "ARDENDO EM FOGO MINH'ALMA ESTÁ" },
  { "number": "788", "name": "IGREJA, TU VAIS SUBIR" },
  { "number": "789", "name": "NA PRESENÇA DE JESUS" },
  { "number": "790", "name": "AQUELE QUE HABITA NO ESCONDERIJO" },
  { "number": "791", "name": "EU QUERO MAIS E MAIS DE CRISTO" },
  { "number": "792", "name": "LOUVANDO A DEUS (AT 2.47)" },
  { "number": "793", "name": "MESA PREPARADA" },
  { "number": "794", "name": "JESUS LIBERTOU" }
];

// Second hymnary (C collection) - you can expand this list with your C hymnary
export const cHymnsDatabase: Hymn[] = [
  { "number": "C01", "name": "MEU DEUS, MEU PAI" },
  { "number": "C02", "name": "PAI, ESTOU A TE CLAMAR" },
  { "number": "C03", "name": "CLAMO, Ó SENHOR POR TEU SANGUE" },
  { "number": "C04", "name": "CLAMO, Ó SENHOR" },
  { "number": "C05", "name": "ESTOU AQUI PRA CONFESSAR" },
  { "number": "C06", "name": "PERDOA-ME, SENHOR" },
  { "number": "C07", "name": "É TEU SANGUE, MEU SENHOR JESUS" },
  { "number": "C08", "name": "DIANTE DO TEU ALTAR" },
  { "number": "C09", "name": "DOBRO OS MEUS JOELHOS" },
  { "number": "C10", "name": "CLAMA, Ó IGREJA" },
  { "number": "C11", "name": "CLAMO A TI, MEU SENHOR E PAI (UMA NOVA CANÇÃO)" },
  { "number": "C12", "name": "PERDOA-ME, SENHOR, SEGUNDO O SEU AMOR" },
  { "number": "C13", "name": "PURIFICADO COM SANGUE ESTOU" },
  { "number": "C14", "name": "TE SUPLICO, Ó DEUS, EM ORAÇÃO" },
  { "number": "C15", "name": "JESUS, VEM ME ABENÇOAR" },
  { "number": "C16", "name": "PAI CELESTE" },
  { "number": "C17", "name": "QUANDO FALO COM DEUS" },
  { "number": "C18", "name": "BUSCAI AO SENHOR" },
  { "number": "C19", "name": "QUANDO DAVI AO SENHOR ORAVA" },
  { "number": "C20", "name": "QUANDO ORO AO SENHOR" },
  { "number": "C21", "name": "SANTO, JUSTO, PRÍNCIPE DA VIDA" },
  { "number": "C22", "name": "FAZE ORAÇÃO" },
  { "number": "C23", "name": "QUANDO ISRAEL SAIU DO EGITO" },
  { "number": "C24", "name": "UMA OVELHINHA DE JESUS EU SOU" },
  { "number": "C25", "name": "ONDE QUER QUE TU FORES, IREI JESUS" },
  { "number": "C26", "name": "EU SOU UMA OVELHINHA DE JESUS" },
  { "number": "C27", "name": "ELE É A RAIZ" },
  { "number": "C28", "name": "SOU UMA CRIANÇA FELIZ" },
  { "number": "C29", "name": "JESUS, QUANDO ME LEMBRO" },
  { "number": "C30", "name": "ELE VIVE EM MIM" },
  { "number": "C31", "name": "EU QUERO SER O SAL DA TERRA" },
  { "number": "C32", "name": "PRÍNCIPE DA PAZ" },
  { "number": "C33", "name": "CRISTO, MEU BOM MESTRE" },
  { "number": "C34", "name": "TENHO UM SENHOR MUITO FORTE" },
  { "number": "C35", "name": "QUERO SER COMO DAVI" },
  { "number": "C36", "name": "EU QUERO ANDAR SEMPRE COM JESUS" },
  { "number": "C37", "name": "NO MEU CORAÇÃO HÁ UM TESOURO (PRÍNCIPE DA VIDA)" },
  { "number": "C38", "name": "TENHO UM CORAÇÃO ALEGRE" },
  { "number": "C39", "name": "NA AREIA NÃO QUERO CONSTRUIR (FIRME, SIM!)" },
  { "number": "C40", "name": "QUERO OUVIR (MEU QUERER)" },
  { "number": "C41", "name": "A MINHA CASA FIRME ESTÁ" },
  { "number": "C42", "name": "MINHA VIDA E MEU CORAÇÃO" },
  { "number": "C43", "name": "SOU FELIZ!" },
  { "number": "C44", "name": "SOU SERVO DO SENHOR" },
  { "number": "C45", "name": "JESUS RESSUSCITOU! (MEU AMIGO JESUS)" },
  { "number": "C46", "name": "COMO É BOM SERVIR A DEUS" },
  { "number": "C47", "name": "TENHO NO MEU CORAÇÃO" },
  { "number": "C48", "name": "JESUS CRISTO É O AMADO" },
  { "number": "C49", "name": "A MINHA ALEGRIA É CRESCER COM O MEU SENHOR" },
  { "number": "C50", "name": "DO ALTO CÉU" },
  { "number": "C51", "name": "EIS-ME AQUI, SENHOR, EM TEU ALTAR" },
  { "number": "C52", "name": "SEU NOME É MARAVILHOSO" },
  { "number": "C53", "name": "É BOM, É BOM DEMAIS" },
  { "number": "C54", "name": "COMO É BOM SABER" },
  { "number": "C55", "name": "É SOMENTE TEU MEU CORAÇÃO" },
  { "number": "C56", "name": "CRISTO É O SENHOR" },
  { "number": "C57", "name": "HÁ UMA LINDA CANÇÃO DE AMOR" },
  { "number": "C58", "name": "VIVER É TÃO LINDO" },
  { "number": "C59", "name": "O NOME DO MEU SENHOR!" },
  { "number": "C60", "name": "DEUS FALOU COMIGO" },
  { "number": "C61", "name": "SEI QUE NA CRUZ SEU SANGUE VERTEU" },
  { "number": "C62", "name": "É TÃO TRISTE NÃO VER A LUZ (CEGO BARTIMEU)" },
  { "number": "C63", "name": "TEM BOM ÂNIMO, POBRE PECADOR" },
  { "number": "C64", "name": "EU VOU CONTAR UMA HISTÓRIA (ZAQUEU)" },
  { "number": "C65", "name": "ONDE NASCEU JESUS?" },
  { "number": "C66", "name": "NASCEU UM NOVO DIA" },
  { "number": "C67", "name": "MARAVILHA É O AMOR DE DEUS" },
  { "number": "C68", "name": "VEM PARA O MEIO (ÁGUAS DA SALVAÇÃO)" },
  { "number": "C69", "name": "VOCÊ SABE O QUE É SALVAÇÃO?" },
  { "number": "C70", "name": "O DIA DO SENHOR VIRÁ (O SOL DA JUSTIÇA)" },
  { "number": "C71", "name": "JESUS VIU A MULTIDÃO (A MULTIPLICAÇÃO)" },
  { "number": "C72", "name": "TU ÉS O CRISTO, O FILHO DO DEUS VIVO" },
  { "number": "C73", "name": "DE ETERNIDADE A ETERNIDADE" },
  { "number": "C74", "name": "AQUILO QUE MELHOR EXISTE" },
  { "number": "C75", "name": "VOCÊ SABE QUEM FOI JOÃO BATISTA?" },
  { "number": "C76", "name": "JESUS FALOU QUE O CÉU É PRA MIM" },
  { "number": "C77", "name": "VOU CONTAR-VOS DE JESUS" },
  { "number": "C78", "name": "O SENHOR É A MINHA LUZ E A MINHA SALVAÇÃO" },
  { "number": "C79", "name": "DEUS AMA VOCÊ" },
  { "number": "C80", "name": "EXISTE UM LUGAR" },
  { "number": "C81", "name": "QUANDO OUVI JESUS ME CHAMAR" },
  { "number": "C82", "name": "JESUS VEM NOS BUSCAR" },
  { "number": "C83", "name": "FOI NO CAMINHO PARA DAMASCO" },
  { "number": "C84", "name": "QUERES SER FELIZ?" },
  { "number": "C85", "name": "NESTE DIA ESPECIAL" },
  { "number": "C86", "name": "UM DIA MORREU O MEU JESUS" },
  { "number": "C87", "name": "O SENHOR É O BOM PASTOR" },
  { "number": "C88", "name": "VOU CONTAR PARA VOCÊ UMA HISTÓRIA ESPECIAL" },
  { "number": "C89", "name": "CERTO HOMEM, PRÍNCIPE DOS JUDEUS (NICODEMOS)" },
  { "number": "C90", "name": "ELE MORREU, MAS RESSURGIU" },
  { "number": "C91", "name": "TENHO ALGO PRA VOCÊ" },
  { "number": "C92", "name": "JESUS CURA E SALVA" },
  { "number": "C93", "name": "JESUS TE AMA" },
  { "number": "C94", "name": "AQUELE QUE TEM SEDE" },
  { "number": "C95", "name": "DO PÃO DO CÉU" },
  { "number": "C96", "name": "SONHEI COM JESUS ESTA NOITE" },
  { "number": "C97", "name": "JESUS É O CAMINHO" },
  { "number": "C98", "name": "EU ABRI MEU CORAÇÃO" },
  { "number": "C99", "name": "NO MEU CORAÇÃO" },
  { "number": "C100", "name": "CRISTO SENTE SEU AMOR POR MIM" },
  { "number": "C101", "name": "JESUS MESMA" },
  { "number": "C102", "name": "DAS MARAVILHAS QUE A BÍBLIA CONTÉM" },
  { "number": "C103", "name": "VINDE, MENINOS" },
  { "number": "C104", "name": "NO CAMINHO ELE ME GUIARÁ" },
  { "number": "C105", "name": "HAVEREMOS DE CHEGAR" },
  { "number": "C106", "name": "JESUS CRISTO É O CAMINHO" },
  { "number": "C107", "name": "EU QUERO CANTAR" },
  { "number": "C108", "name": "HOJE É UM GRANDE DIA" },
  { "number": "C109", "name": "CANTA, ALEGREMENTE, Ó FILHA DE SIÃO" },
  { "number": "C110", "name": "EU TUDO POSSO NAQUELE QUE ME FORTALECE" },
  { "number": "C111", "name": "ENTREGA O TEU CAMINHO" },
  { "number": "C112", "name": "CONSOLA-ME, ESPÍRITO SANTO" },
  { "number": "C113", "name": "TUA MÃO É PODEROSA" },
  { "number": "C114", "name": "O SENHOR É QUEM CUIDA DE MIM" },
  { "number": "C115", "name": "JESUS, O BOM PASTOR" },
  { "number": "C116", "name": "SOBRE AS ONDAS" },
  { "number": "C117", "name": "DEITADA NA RELVA UMA FELIZ OVELHA" },
  { "number": "C118", "name": "ÂNCORA SEGURA" },
  { "number": "C119", "name": "JESUS, O MELHOR AMIGO" },
  { "number": "C120", "name": "PODERÁ CANTAR" },
  { "number": "C121", "name": "MEU BARQUINHO" },
  { "number": "C122", "name": "CRISTO É MEU AMIGO" },
  { "number": "C123", "name": "NESTA BATALHA NÃO TEREIS QUE PELEJAR" },
  { "number": "C124", "name": "O CÉU E A TERRA PASSARÃO" },
  { "number": "C125", "name": "COM JESUS VENCEDOR SEREI" },
  { "number": "C126", "name": "DEUS FORTE COMO JEOVÁ" },
  { "number": "C127", "name": "CRISTO É VITÓRIA" },
  { "number": "C128", "name": "CRISTO É MEU AMIGO, É MEU AMIGO" },
  { "number": "C129", "name": "ONTEM, HOJE E PARA SEMPRE" },
  { "number": "C130", "name": "MEU BOM PASTOR É CRISTO" },
  { "number": "C131", "name": "COM CRISTO NO BARCO" },
  { "number": "C132", "name": "MEU BARCO É PEQUENO" },
  { "number": "C133", "name": "JESUS VÊ A SUA IGREJA" },
  { "number": "C134", "name": "VOU CAMINHANDO PRA JERUSALÉM" },
  { "number": "C135", "name": "FLUA EM MIM, SENHOR" },
  { "number": "C136", "name": "LÂMPADA PARA OS MEUS PÉS" },
  { "number": "C137", "name": "NÃO POR FORÇA" },
  { "number": "C138", "name": "SOU UM SOLDADO DO BOM SALVADOR" },
  { "number": "C139", "name": "DONS DO ESPÍRITO SANTO" },
  { "number": "C140", "name": "UMA LUZ RESPLANDECENTE" },
  { "number": "C141", "name": "QUEM IRÁ? (PRECIOSA SEMENTE)" },
  { "number": "C142", "name": "COMO UMA FOLHA AO VENTO" },
  { "number": "C143", "name": "TENHO UMA CANDEIA (CANDEIA ACESA)" },
  { "number": "C144", "name": "NOVA ALIANÇA" },
  { "number": "C145", "name": "REVELAÇÃO ABRE PRA VOCÊ" },
  { "number": "C146", "name": "A IGREJA QUE ORA É VITORIOSA" },
  { "number": "C147", "name": "EM TUAS PISADAS" },
  { "number": "C148", "name": "ANDANDO EM ESPÍRITO (FRUTO DO ESPÍRITO)" },
  { "number": "C149", "name": "NÓS SOMOS UMA VOZ" },
  { "number": "C150", "name": "CINCO SEIXOS" },
  { "number": "C151", "name": "NO PRINCÍPIO ERA O VERBO" },
  { "number": "C152", "name": "NAS BATALHAS SOU UM VENCEDOR (ARMADURA DE DEUS)" },
  { "number": "C153", "name": "COMO NOÉ" },
  { "number": "C154", "name": "COM O ESPÍRITO DE DEUS EM MINHA VIDA" },
  { "number": "C155", "name": "QUERO ESTAR EM TUA PRESENÇA, Ó DEUS" },
  { "number": "C156", "name": "SOMOS CIDADÃOS DO CÉU" },
  { "number": "C157", "name": "ESTE MUNDO NÃO É MEU LUGAR" },
  { "number": "C158", "name": "NO CAMINHO EU QUERO ESTAR" },
  { "number": "C159", "name": "SOU SERVO DO SENHOR" },
  { "number": "C160", "name": "EXISTEM SEGREDOS NA TUA PALAVRA" },
  { "number": "C161", "name": "TU ÉS PRA MIM UM VASO ESCOLHIDO" },
  { "number": "C162", "name": "ANDAI NA MINHA PRESENÇA" },
  { "number": "C163", "name": "DÁ-ME UM CORAÇÃO CHEIO DO TEU AMOR" },
  { "number": "C164", "name": "DÁ-ME UM CORAÇÃO HUMILDE E RETO" },
  { "number": "C165", "name": "QUERO SER SANTO PARA O SENHOR" },
  { "number": "C166", "name": "BRILHANDO, BRILHANDO" },
  { "number": "C167", "name": "DANIEL NA COVA DOS LEÕES" },
  { "number": "C168", "name": "JESUS CHAMA OS SEUS MINISTROS" },
  { "number": "C169", "name": "SETE CARTAS" },
  { "number": "C170", "name": "NÓS SOMOS A CARTA DE CRISTO" },
  { "number": "C171", "name": "SOU O SANTO" },
  { "number": "C172", "name": "QUATRO COISAS TÃO PEQUENINAS" },
  { "number": "C173", "name": "OUÇO O CLAMOR DO BOM PASTOR" },
  { "number": "C174", "name": "A TUA PALAVRA É SEMENTE" },
  { "number": "C175", "name": "UM CERTO PASTORZINHO" },
  { "number": "C176", "name": "CRIA EM MIM, Ó DEUS" },
  { "number": "C177", "name": "FALA AO MEU CORAÇÃO, JESUS" },
  { "number": "C178", "name": "DISSE JESUS AOS JUDEUS (EU TRABALHO TAMBÉM)" },
  { "number": "C179", "name": "ORAR FAZ BEM" },
  { "number": "C180", "name": "QUERO SER FIEL (JESUS ESTÁ VIVO)" },
  { "number": "C181", "name": "JERUSALÉM, CIDADE DO MEU REI" },
  { "number": "C182", "name": "QUERO VIVER PARA SEMPRE COM JESUS" },
  { "number": "C183", "name": "UM NOVO CÉU, UMA NOVA TERRA SE FARÁ" },
  { "number": "C184", "name": "NO EXPRESSO VIAJAMOS" },
  { "number": "C185", "name": "HÁ UMA LINDA MORADA" },
  { "number": "C186", "name": "NOSSAS VIDAS SÃO MUDADAS" },
  { "number": "C187", "name": "VARÕES GALILEUS" },
  { "number": "C188", "name": "JERUSALÉM ANSEIO VER" },
  { "number": "C189", "name": "UM DIA A IGREJA SUBIRÁ" },
  { "number": "C190", "name": "IGREJA, CORPO DE CRISTO" },
  { "number": "C191", "name": "A NOIVA AMADA DO CORDEIRO" },
  { "number": "C192", "name": "VOU PRA JERUSALÉM" },
  { "number": "C193", "name": "HÁ UMA IGREJA QUE AGUARDA O SENHOR" },
  { "number": "C194", "name": "NA NOVA JERUSALÉM" },
  { "number": "C195", "name": "EM BREVE ESTAREMOS NA GLÓRIA" },
  { "number": "C196", "name": "JESUS NOS PROMETEU" },
  { "number": "C197", "name": "MARANATA! VEM, SENHOR JESUS" },
  { "number": "C198", "name": "O DIA ESTÁ CHEGANDO" },
  { "number": "C199", "name": "AGUARDANDO A ORIENTAÇÃO DO SALVADOR" },
  { "number": "C200", "name": "VOU PARA O MEU LAR" },
  { "number": "C201", "name": "SOBRE AS NUVENS JESUS VEM" },
  { "number": "C202", "name": "A RAABE VEIO A ORDEM" },
  { "number": "C203", "name": "O FIO DE ESCARLATA É O MISTÉRIO" },
  { "number": "C204", "name": "\"MARCHAI\"! \"MARCHAI\"!" },
  { "number": "C205", "name": "A MINHA ALMA ESPERA" },
  { "number": "C206", "name": "NO CÉU UM DIA NÓS VAMOS MORAR" },
  { "number": "C207", "name": "JESUS PROMETEU NOS BUSCAR" },
  { "number": "C208", "name": "EU QUERO IR PARA O CÉU" },
  { "number": "C209", "name": "SE EU FALO DO GRANDE AMOR DO PAI" },
  { "number": "C210", "name": "JESUS VOLTARÁ PRA ME BUSCAR! (MARANATA)" },
  { "number": "C211", "name": "OS DIAS ESTÃO PASSANDO" },
  { "number": "C212", "name": "SEI QUE CRISTO VOLTARÁ" },
  { "number": "C213", "name": "LÁ NO DOCE PORVIR" },
  { "number": "C214", "name": "NÓS RECEBEREMOS LÁ NO CÉU" },
  { "number": "C215", "name": "EIS QUE JESUS VEM NAS NUVENS" },
  { "number": "C216", "name": "SOBRE AS NUVENS DESCERÁ (ELE VIRÁ)" },
  { "number": "C217", "name": "VEREI MEU GRANDE REI" },
  { "number": "C218", "name": "MARANATA" },
  { "number": "C219", "name": "ELE VIRÁ NO MEIO DA NOITE" },
  { "number": "C220", "name": "ONDE VIVE O REI DA GLÓRIA?" },
  { "number": "C221", "name": "VAI RAIAR O DIA" },
  { "number": "C222", "name": "DEUS HABITA NO MEIO DOS LOUVORES" },
  { "number": "C223", "name": "PAI, TUA BELEZA ME ADMIRA" },
  { "number": "C224", "name": "DEUS CRIOU OS CÉUS E A TERRA" },
  { "number": "C225", "name": "EU VIM AQUI, SENHOR" },
  { "number": "C226", "name": "IREI CANTAR E ADORAR O REI JESUS" },
  { "number": "C227", "name": "A JESUS IREI LOUVAR" },
  { "number": "C228", "name": "HOSANA AO FILHO DE DAVI" },
  { "number": "C229", "name": "CANTAI ALEGREMENTE A DEUS" },
  { "number": "C230", "name": "ESTA CANÇÃO" },
  { "number": "C231", "name": "TODO SER QUE TEM FÔLEGO" },
  { "number": "C232", "name": "HOJE EU NÃO QUERO PEDIR" },
  { "number": "C233", "name": "NA CIDADE DE DAVI NASCEU O SALVADOR" },
  { "number": "C234", "name": "SEI QUE SOU AMADO DO MEU SALVADOR" },
  { "number": "C235", "name": "SENHOR, EU TE LOUVAREI" },
  { "number": "C236", "name": "SENHOR, DEUS TU ÉS VARÃO DE GUERRA" },
  { "number": "C237", "name": "MUITOS MOTIVOS TENHO" },
  { "number": "C238", "name": "EU VOU CANTAR" },
  { "number": "C239", "name": "JESUS É A NOSSA VITÓRIA" },
  { "number": "C240", "name": "O SENHOR DOS EXÉRCITOS ESTÁ AQUI" },
  { "number": "C241", "name": "EXALTAI, EXALTAI" }
];

// Public hymns database - populated from the server
export let aHymnsDatabase: Hymn[] = [];

export const setAHymnsDatabase = (hymns: Hymn[]) => {
  aHymnsDatabase = hymns;
};

// Helper function to determine which database to use based on the query
const getActiveDatabase = (query: string): Hymn[] => {
  const upperQuery = query.toUpperCase().trim();
  if (upperQuery.startsWith('C')) {
    return cHymnsDatabase;
  }
  if (upperQuery.startsWith('A')) {
    return aHymnsDatabase;
  }
  return hymnsDatabase;
};

// Helper functions for searching hymns
export const searchHymnsByName = (query: string): Hymn[] => {
  if (!query.trim()) return [];
  
  const normalizedQuery = query.toUpperCase().trim();
  
  // Search in all databases
  const defaultResults = hymnsDatabase.filter(hymn =>
    hymn.name.includes(normalizedQuery)
  );
  
  const cResults = cHymnsDatabase.filter(hymn =>
    hymn.name.includes(normalizedQuery)
  );
  
  const aResults = aHymnsDatabase.filter(hymn =>
    hymn.name.includes(normalizedQuery)
  );
  
  return [...defaultResults, ...cResults, ...aResults].slice(0, 10); // Limit to 10 results
};

export const searchHymnsByNumber = (query: string): Hymn[] => {
  if (!query.trim()) return [];
  
  const activeDatabase = getActiveDatabase(query);
  
  return activeDatabase.filter(hymn =>
    hymn.number.startsWith(query.trim())
  ).slice(0, 10); // Limit to 10 results
};

export const getHymnByNumber = (number: string): Hymn | undefined => {
  const trimmedNumber = number.trim();
  const activeDatabase = getActiveDatabase(trimmedNumber);
  return activeDatabase.find(hymn => hymn.number === trimmedNumber);
};

export const getHymnByName = (name: string): Hymn | undefined => {
  const normalizedName = name.toUpperCase().trim();
  
  // Search in all databases
  let result = hymnsDatabase.find(hymn => hymn.name === normalizedName);
  if (!result) {
    result = cHymnsDatabase.find(hymn => hymn.name === normalizedName);
  }
  if (!result) {
    result = aHymnsDatabase.find(hymn => hymn.name === normalizedName);
  }
  
  return result;
};
